#Inspired by https://github.com/jasonyang-ee/STM32-Dockerfile/tree/main
FROM docker.io/alpine:3.23.4

RUN set -eux; \
    apk add --no-cache --virtual build-dependencies \
        build-base=0.5-r3 \
        gcc=15.2.0-r2 \
        gcc-arm-none-eabi=15.2.0-r1  \
        cmake=4.1.3-r0 \
        newlib=4.5.0.20241231-r0  \
    ;

WORKDIR /app

COPY . .

ARG LCD_CONTROLLER=ST7789
ARG LCD_SIZE=240X320
ARG LCD_ROTATION=2
ARG FW_VERSION=dev

RUN set -eux; \
    cmake -S . -B build \
        -DLCD_CONTROLLER=${LCD_CONTROLLER} \
        -DLCD_SIZE=${LCD_SIZE} \
        -DLCD_ROTATION=${LCD_ROTATION} \
        -DFW_VERSION=${FW_VERSION}; \
    cmake --build build -j$(nproc);
